version: '3'

services:
    app:
        image: node:20
        container_name: spinalcom-exercice
        command: npm run serve
        working_dir: /app
        ports:
            - 8080:8080
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
